### ISSUE TITLE
Job ID support?

### ISSUE THREAD

**Issue by bitwombat** [jessetane/queue#10]
Any way I can identify jobs so I know which job finished when 'success' is emitted, not by the 'job' string (which may be long), but by a number?  Sort of like PID does for shell?

I'm using queue to do concurrently process lots of files (via child_process.exec).

**Comment by jessetane** [comment]
Since functions in javascript are also objects, would it be possible for you to set your id as a property on the job itself? The argument passed to the success event should be the job itself, not a string.

I included an example of one way to do this in #6 

Definitely open to other ideas though, let me know what you think.

**Comment by gbell12** [comment]
Read your gist, but your Fetcher is over my head a bit...

Setting the id as a property on the job... the job has to be a function, which a single callback parameter, right?

I'm already passing a function (returned by another) since I don't want a closure.
````
for (var i=0; i<files.length; ++i) {
    q.push(worker(i));
}
````

Is this close?

**Comment by jessetane** [comment]
http://requirebin.com/?gist=3a7898355a811b388b5d

any better?

**Comment by jessetane** [comment]
I don't usually find myself needing to do things like this though, do you have a more complete example? Maybe there is another way around the problem.

**Comment by gbell12** [comment]
I didn't know you could attach arbitrary properties to function objects.  Javascript noob, sorry for bothering you with that.  That solution will work great, thanks.
