### ISSUE TITLE
A little bit confused by timeoutId

### ISSUE THREAD

**Issue by ash0080** [jessetane/queue#66]
```
this.timers[timeoutId] = timeoutId
```

actually setTimeout return an object in Node.js
so the key in this.timers is '[object object]' 
so it will be override every time
so the timer always hold only one child

maybe not works as you expected?

**Comment by jessetane** [comment]
yikes, you're right - in node at least. in the browser `setTimeout` returns an integer which can get cast to a unique string to be used as the key... thanks for pointing this out though, any ideas on what we should do?

**Comment by ash0080** [comment]
1. simple one,  using an internal counter as uuid ,  maybe let Integer overflow, but works for 99.999% usage.
2. using weak map to store timers, then you can using function or object as key like normal

**Comment by jessetane** [comment]
@ash0080 care to send a patch?

**Comment by ash0080** [comment]
Wish to, but actually my folk changed everything.
so it's would not be a patch, but absolutely another thing.  hahhhhhh...

**Comment by mpvosseller** [comment]
I noticed this bug and was going to suggest a combination of `Date.now()` and `Math.random()`
```javascript
timeoutId = `${Date.now()}${Math.random()}` // '16234269777330.8934721663218723'
```

However, I wasn't able to actually reproduce the bug in Node. Turns out in Nonde v14.9.0 and v12.19.0 they added a method to the `Timeout` object [`[Symbol.toPrimitive]`](https://nodejs.org/api/timers.html#timers_timeout_symbol_toprimitive) which converts it to a number. As such it now "just works" and a compatible number is used as the key.

Unless you want to support older versions of Node I think you can close this.

**Comment by jessetane** [comment]
Thanks for the note! Closing for now then.
